name: AI Test Generation
on:
  issues:
    types: [labeled, opened]
  workflow_dispatch:
    inputs:
      issue_title:
        description: 'Issue title for test generation'
        required: false
        default: 'Manual test generation'
      issue_body:
        description: 'Issue description'
        required: false
        default: 'Generate unit tests manually'

jobs:
  generate-tests:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.issue.labels.*.name, 'ai-test-generation') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Clone Universal C Test Generator
        run: |
          git clone https://github.com/SwathantraPulicherla/Gemini-Agent-and-api.git test-generator
          
      - name: Copy build system and testing framework
        run: |
          cp test-generator/Makefile .
          cp -r test-generator/unity .
          cp test-generator/CMakeLists.txt .
          
      - name: Install Python dependencies
        run: |
          pip install google-generativeai python-dotenv
          
      - name: Create test directory
        run: |
          mkdir -p tests/generated
          
      - name: Generate tests with AI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title || github.event.inputs.issue_title || 'Manual test generation' }}
          ISSUE_BODY: ${{ github.event.issue.body || github.event.inputs.issue_body || 'Generate unit tests manually' }}
        run: |
          python scripts/ai_test_generator.py
          
      - name: Verify generated tests
        run: |
          echo "Generated tests:"
          ls -la tests/generated/
          if [ -f tests/generated/generated_tests.c ]; then
            echo "Test file created successfully"
            cat tests/generated/generated_tests.c | head -20
          else
            echo "No test file generated"
            exit 1
          fi
          
      - name: Commit and push generated tests
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tests/ unity/ Makefile CMakeLists.txt
          git commit -m "Add AI-generated test cases and build system for issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }} || echo "No changes to push"
          
      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./test_temperature_sensor